* South West Thing

** Districts Rep

[List of shit that Imo has written down.]

** Motions

*** Late Motion 2

Amendment passes unanimously.

Motion clearly passes.

*** Late Motion 6

Motion passes 9/0/1.

** International Delegation at an Event

Yes, to DF Camp (not Spring Awakening).

Discussion was had about suggestions and potential issues, Anna (Intl. Rep) took notes.

*** Funding

Sources of funding:
- ERASMUS Plus (would have to wait till next year)
- ESPLAC
- IFM
- DFs

If they're flying, we will need to provide tents and equipment.

Could ask them to find funding from Spain because it might be easier that way round.

*** Hosting

Imo to talk to Bradford DFs, Anna to check out other districts which have hosted before.

** Woodcraft Communities

Lily did a presentation

** Scottish Thing

Scottish schools have already finished at Scottish Thing so people will be going away.  We agreed to swap Midlands and Scottish Things.

** Closed Committee Meeting

*** General Council

GC have budgeted the £4000 again for next year's budget.  This is not OK by most of committee as it was specifically said to be a one-off.  Not to say we shouldn't financially support them, but we're not going to throw money away.  E.g. funding VC, an issue of the Courier.

**** ACTION: GC Reps to let GC know about this ASAP.

*** GC Reps

We should advertise the vacancy and if nobody takes it up then we shouldn't have the election.


** Committee Feedback

[Reports written for all but Secretary, Districts, Affiliations, Treasurer[fn:1], MEST-UP.  Received written reports.]

*** Secretary

Done very little: taking minutes, typing them up.  Still to do musings from Althing.

**** ACTION: Secretary to update the constitution and DPs.

**** ACTION: Secretary to write another page on STW.


*** Discussion about Winter Wonderland

Venues for WW are really hard to find.  Resolved to have SA and DF Camp reasonably north to compensate having continually in Bristol.

** Event Feedback

Feedback for this event was:

*** Venue

- Closer to train stations
- Somewhere where buses exist
- Liked the stove
- Joe F enjoyed last night
- Individuadual bedrooms
- Enjoyed the double bunk beds
- Winter Things should have heating
- Ask about wifi

*** Food

- Check and update allergy requirements
- Lots of food
- Vegan alternatives non-existant
- Haven't seen KPs much -- think about inclusiveness of Things.

*** General

- Some problems with drugs being too overt (preparation, not consumption).
- Felt very productive
- Occasionally, discussion went round in circles
- Lots of actions
- Make more non-Committee come to Things
- More evening programme

* Quotes

"It's just like snorting things and swallowing things -- some things aren't meant to go up your nose.  Dye that goes on hair up here can't always go on hair down there." -- Kitty Howse

"To be honest, I've always found my crotch is a solution." -- Joe Flannagan

"If your internal organs are outside of you, your opinions don't count." -- Louise Delmege

* Footnotes

[fn:1] Joe B gave a Treasurer report on Ellie's behalf.

