* Attendance
Naomi Wilkins, Ruth Mestel, Josh Hope-Collins, Lily MacTaggart, Lily Bowler, Ellie Mestel, Toby Hanson-Iles, Issy Hadlum, Charlotte Stait, ?, ?, Mike ?, Georgia (from Leicester), Pip (from Bradford), that guy from Cov, Esther Rathbone, Anna Rathbone, ?, ?, Pat, Seif, Joe Bowler, Joe MacMahummanahummus.

Question marks are usually from Manchester, check your cliquey privilege.

* General business
** Mock election

Decided to elect an 'Advanced Banterer'.

Nominated: Josh, Anna, Seif, Pat.

Josh elected by majority.

** Motion 14

Votes 16 for; 4 against; 1 abstention.

** Motion 15

Decided to leave till the end of the mini-Thing.

Decided to ask some questions to proposer before further discussion.

*** Questions to Kitty
- Why only women & trans*?
- Why mandatory?
- How is this different to current practice?

** Advertising for Spring Awakening
Apparently, Banbury is near Oxford.  Ceilidgh dancing.  MAYBE EVEN GRACE PETRIE and Henry.

** DF Camp
- Lots of evening programme that is not loud
- Maybe 4 nights out of 6 with amplified music, DJs, etc.
- Unfair to ask first-aid people to deal with heavy drug use.  Maybe put impact on FA team in D&A policy.
- Good brandy.
- This is a lot of negative feedback but in general DF Camp 13 was pretty damn tasty.

* 16-25 Events
- This event has been good.
- Should keep 3 main social events as DF-only events and other events can do what the fuck the like innit.
- DFs is about youth empowerment and if all important roles on events are taken by >21 year olds it becomes problematic.
- New group called Kinspholk with age-range 16-25.

* MEST-UP Online
Put shit online idk or something.

* Quotes
"Shatner the banter." -- Joe Bowler
"Shatner." -- Literally everybody
"This isn't banter, this is bullshit." -- Joe MacMahon
